#!/bin/bash

# ---

# usage function:
function usage() {
  echo "$(basename ${0}) host python-envname"
  exit
}

# check arguments:
if [ "${#}" -lt 1 ] ; then
  usage
fi

# arguments:
REMOTE_HOST="${1}"
PYTHON_LOAD="conda activate ${2}"

# pick a random port:
PORT=$((20000 + $((RANDOM % 40000))))

# SSH to remote host and start the notebook:
ssh \
  -q \
  -t \
  -J foe-linux-04 \
  ${REMOTE_HOST} \
  -L ${PORT}:localhost:${PORT} \
  -t "${PYTHON_LOAD} ; \
      jupyter notebook --port=${PORT} --no-browser"
